# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do |options|
  desc "Update project version and build numbers"
  lane :versions do |options|
    # increment_version_number({
    #   version_number: "#{options[:versionNumber]}"
    # })
    increment_build_number({
      build_number: options[:buildNumber]
    })
  end

  desc "Push a new beta build to TestFlight"
  lane :upload do |options|
    app_store_connect_api_key(
      key_id: options[:apiKeyId],
      issuer_id: options[:apiKeyIssuerId],
      key_filepath: options[:apiKeyFilePath]
    )
    upload_to_testflight({
      ipa: options[:ipaPath],
      app_version: options[:versionNumber],
      build_number: options[:patch],
      skip_waiting_for_build_processing: true,
      changelog: "CI-#{options[:versionNumber]}-#{options[:patch]}"      
    })
  end
end
